name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint@7.x eslint-config-airbnb@18.x eslint-plugin-import@2.x eslint-plugin-jsx-a11y@6.x eslint-plugin-react@7.x eslint-plugin-react-hooks@4.x @babel/eslint-parser@7.x @babel/core@7.x  @babel/plugin-syntax-jsx@7.x @babel/preset-env@7.x  @babel/preset-react@7.x
          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.eslintrc.json
          [ -f .babelrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.babelrc
      - name: ESLint Report
        run: npx eslint "**/*.{js,jsx}"
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi





          # Module 2 Capstone Pokemon

<a name="readme-top"></a>

<div align="center">

  <br/>

  <h3><b>Module 2 Capstone Pokemon</b></h3>
  <p>In this project I will be using webpack to bundle my code, the project is about using multiple APIs to show and manipulate data. Styling is done with sass. Jest testing is used for the project. It will include mainly JS, HTML, Sass, and JSON</p>

<div align="center">
  <img src="assests/images/Personal-portfolio-with-play.gif"  alt="Personal portfolio video">
  <br>
   <a href="https://drive.google.com/file/d/1AN1Oph1s-dFzk4pkKvT0cJqSd7RgNPuf/view?usp=sharing">Watch full video </a>
</div>

</div>

# ğŸ“— Table of Contents

- [Module 2 Capstone Pokemon](#Module2Capstone_Pokemon)
- [ğŸ“— Table of Contents](#-table-of-contents)
- [ğŸ“– Module 2 Capstone Pokemon< ](#Module2Capstone_Pokemon)
- [ğŸš€ Live Demo ](#-live-demo-)
- [ğŸ“– Module 2 Capstone Pokemon< ](#Module2Capstone_Pokemon)
  - [ğŸ›  Built With HTML, CSS and JavaScript](#-built-with-html-css-and-javascript)
    - [Tech Stack ](#tech-stack-)
    - [Key Features ](#key-features-)
  - [ğŸ’» Getting Started ](#-getting-started-)
    - [Prerequisites](#prerequisites)
    - [Setup](#setup)
    - [Install](#install)
  - [ğŸ‘¥ Authors ](#-authors-)
  - [ğŸ”­ Future Features ](#-future-features-)
  - [ğŸ¤ Contributing ](#-contributing-)
  - [â­ï¸ Show your support ](#ï¸-show-your-support-)
  - [ğŸ™ Acknowledgments ](#-acknowledgments-)
  - [â“ FAQ ](#-faq-)
  - [ğŸ“ License ](#-license-)

# ğŸ“– Module 2 Capstone Pokemon< <a name="about-project"></a>

**Module 2 Capstone Pokemon<e**
In this project I will be using webpack to bundle my code, the project is about using multiple APIs to show and manipulate data. Styling is done with sass. Jest testing is used for the project. It will include mainly JS, HTML, Sass, and JSON.

## ğŸš€ Live Demo <a name="live-demo"></a>

- [Live Demo Link](https://geekyhacks.github.io/Module2Capstone_Pokemon/dist/.)

# ğŸ“– Module 2 Capstone Pokemon <a name="live-demo"></a>

## ğŸ›  Built With <a name="built-with">HTML, CSS and JavaScript</a>

### Tech Stack <a name="tech-stack"></a>

  <ul>
    <li><a href="https://developer.mozilla.org/ru/docs/Web/HTML">HTML</a></li>
    <li><a href="https://developer.mozilla.org/ru/docs/Web/CSS">CSS</a></li>
    <li><a href="https://developer.mozilla.org/ru/docs/Web/JavaScript">JavaScript</a></li>
    <li><a href="https://sass-lang.com/">sass</a></li>
    <li><a href="https://www.json.org/json-en.html">json</a></li>
  </ul>

### Key Features <a name="key-features">

</a>

- API
- Webpack
- Jest
- Sass

<p align="right">(<a href="#readme-top">back to top</a>)</p>

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## ğŸ’» Getting Started <a name="getting-started"></a>

To get a local copy up and running, follow these steps:

- Open your Terminal in your VSCode.
- Navigate to the desired directory[folder] to which you want to clone the repository to
- [Copy & Paste] git clone you find in the code button https://github.com/GeekyHacks/Module2Capstone_Pokemon.git

### Prerequisites

In order to run this project you need:

- General Understanding of HTML & CSS
- basic Knowledge of Git Commands
- basic Knowledge of the Terminal Commands
- General Understanding of [bundling](https://youtu.be/5IG4UmULyoA) and [webpack](https://youtu.be/IZGNcSuwBZs)

### Setup

Clone this repository to your desired folder:

- git clone https://github.com/GeekyHacks/Module2Capstone_Pokemon.git

Example commands:

```sh
  cd my-folder
  git clone https://github.com/GeekyHacks/Module2Capstone_Pokemon.git

```

--->

### Install

Must-Install-Project-with-the-Following-Programmes:

- [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) Extention in VScode
- [Git](https://git-scm.com/downloads)
- [Node.js](https://nodejs.org/en/download)
- [npm install](https://docs.npmjs.com/cli/v8/commands/npm-install)
- [webpack](https://webpack.js.org/guides/installation/)
- [Jest](https://jestjs.io/docs/getting-started)

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## ğŸ‘¥ Authors <a name="authors"></a>

ğŸ‘¤ **GeekyHacks**

- GitHub: [Geekyhacks](https://github.com/GeekyHacks)
- Twitter: [Geekydart](https://twitter.com/GeekyDart)
- LinkedIn: [Abdullah Nasser](https://www.linkedin.com/in/abdullah-nasser-711625268/)

## ğŸ”­ Future Features <a name="future-features"></a>

- Adding more webpack deps

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## ğŸ¤ Contributing <a name="contributing"></a>

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](https://github.com/GeekyHacks/Module2Capstone_Pokemon/issues).

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## â­ï¸ Show your support <a name="support"></a>

If you like this project please don't hesitate to support me with your valued contribution and don't forget to star the repo to reach more
people.

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## ğŸ™ Acknowledgments <a name="acknowledgements"></a>

I would like to thank...

- Microverse Review Team
- My Coding Partner @firstpj
- Microverse Community in Slack
- my Mentor @Strangeal
- [Pokemon API](https://pokeapi.co/)

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## â“ FAQ <a name="faq"></a>

Can I clone this project ?\*\*

- Of course you can as long as you fork it and star it

Can I contribute to this project?\*\*

- definitely you can

<p align="right">(<a href="#readme-top">back to top</a>)</p>

## ğŸ“ License <a name="license"></a>

This project is [MIT](LICENSE) licensed.

<p align="right">(<a href="#readme-top">back to top</a>)</p>
